name: 'Authenticate SteamCMD'
description: 'Authenticate with SteamCMD by decoding Steam `config.vdf` from a repository secret.'
author: 'Lordfirespeed'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'purple'

# Define your inputs here.
inputs:
  steam_config_vdf:
    description: "Base64 encoded config.vdf file"
    required: true
  steam_username:
    description: "Username of Steam account to attempt login with"
    required: true
  steam_home:
    description: "Steam configuration root directory"
    default: "$HOME/Steam"

# Define your outputs here.
outputs:

runs:
  using: node20
  main: dist/index.js
