#!/bin/bash

# Runs workflows locally using https://github.com/nektos/act

npm install
npm run build

act -P ubuntu-latest=catthehacker/ubuntu:act-latest --secret-file act-secrets.env -j test-action -W .github/workflows/ci.yml

"$@"
